version: "3.8"

services:
  # BOOKING DB
  booking-postgres:
    image: postgres:16
    container_name: booking-postgres
    restart: always
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: BookingPass123!
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - booking_postgres_data:/var/lib/postgresql/data
    networks:
      - booking-net
  # AUTH DB

  auth-postgres:
    image: postgres:16
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5434:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - booking-net

  # MONGODB (for availability-service)
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - booking-net

  # ZOOKEEPER + KAFKA
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - booking-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - booking-net
  # AUTH SERVICE (FLASK)
  auth-service:
    build: ./backend/authentication-service
    container_name: auth-service
    depends_on:
      - auth-postgres
    ports:
      - "5000:5000"
    environment:
      DB_HOST: auth-postgres
      DB_PORT: "5432"
      DB_NAME: auth_db
      DB_USER: user
      DB_PASSWORD: password
      JWT_SECRET_KEY: "ThisIsA32ByteMinimumSecretKey!!!1234"
    networks:
      - booking-net

  # AVAILABILITY SERVICE
  availability-service:
    build: ./backend/availability-service
    container_name: availability-service
    depends_on:
      - mongodb
    ports:
      - "8090:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/availability_db
    networks:
      - booking-net

  # BOOKING SERVICE
  booking-service:
    build: ./backend/booking-service
    container_name: booking-service
    depends_on:
      - kafka
      - booking-postgres
      - availability-service
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8080

      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-postgres:5432/booking_db
      SPRING_DATASOURCE_USERNAME: booking_user
      SPRING_DATASOURCE_PASSWORD: BookingPass123!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      AVAILABILITY_BASE_URL: http://availability-service:8080
      JWT_SECRET_KEY: "ThisIsA32ByteMinimumSecretKey!!!1234"
    networks:
      - booking-net

  # NOTIFICATION SERVICE
  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8082
    networks:
      - booking-net
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_AUTH_BASE_URL: "http://localhost:5000"
      NEXT_PUBLIC_BOOKING_BASE_URL: "http://localhost:8080"
      NEXT_PUBLIC_AVAILABILITY_BASE_URL: "http://localhost:8090"
    depends_on:
      - auth-service
      - booking-service
      - availability-service
    networks:
      - booking-net

volumes:
  booking_postgres_data:
  auth_postgres_data:
  mongo_data:

networks:
  booking-net:
    driver: bridge
