apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-backend
  template:
    metadata:
      labels:
        app: booking-backend
    spec:
      containers:
        - name: booking-backend
          image: booking-backend:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-backend
spec:
  selector:
    app: booking-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
