apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-frontend
  template:
    metadata:
      labels:
        app: booking-frontend
    spec:
      containers:
        - name: booking-frontend
          image: booking-frontend:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            # your frontend should call backend using service DNS
            - name: NEXT_PUBLIC_API_BASE
              value: "http://booking-backend:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-frontend
spec:
  selector:
    app: booking-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
